# Generated by Django 2.0.3 on 2018-06-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(choices=[('funny', 'Funny'), ('inspirational', 'Inspirational'), ('political', 'Political'), ('parksandRec', 'ParksandRec'), ('sarcasm', 'Sarcasm'), ('courage', 'Courage'), ('music', 'Music'), ('happy', 'Happy'), ('hope', 'Hope'), ('peace', 'Peace')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('inspiration', models.TextField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Artist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Art_Category')),
            ],
        ),
    ]
