# Generated by Django 2.0.3 on 2018-06-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180604_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='inspiration',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_text',
            field=models.CharField(max_length=100),
        ),
    ]
