# Generated by Django 2.0.3 on 2018-06-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180605_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_text',
            field=models.CharField(choices=[('funny', 'Funny'), ('inspirational', 'Inspirational'), ('political', 'Political'), ('sarcasm', 'Sarcasm'), ('courage', 'Courage'), ('music', 'Music'), ('happy', 'Happy'), ('hope', 'Hope'), ('peace', 'Peace'), ('outdoors', 'Outdoors')], max_length=100),
        ),
    ]
