# Generated by Django 2.0.3 on 2018-06-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180605_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_text',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
