# Generated by Django 2.0.3 on 2018-06-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20180605_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, upload_to='items/%Y/%m/%d'),
        ),
    ]
