# Generated by Django 2.0.3 on 2018-06-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_artwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
