# Generated by Django 2.0.3 on 2018-06-06 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180606_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_text',
            field=models.CharField(choices=[('funny', 'Funny'), ('inspirational', 'Inspirational'), ('political', 'Political'), ('sarcasm', 'Sarcasm'), ('courage', 'Courage'), ('music', 'Music'), ('happy', 'Happy'), ('hope', 'Hope'), ('peace', 'Peace'), ('outdoors', 'Outdoors')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
